package com.mycompany.myapp;


import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.FontImage;
import com.codename1.ui.Toolbar;
import java.io.IOException;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class MyApplication {

    private Form current,page1,page2,page3;
    private Resources theme;

    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature, uncomment if you have a pro subscription
        // Log.bindCrashProtection(true);
    }
    
    public void start() {
        if(current != null){
            current.show();
            return;
        }
        Form hi = new Form("Accueil");
       hi.getToolbar().addCommandToSideMenu("Page 1", null, e->{
           page1=new Form("Page 1");
           page1.getToolbar().addCommandToLeftBar("back", theme.getImage("back-command.png"), ev->{
               hi.show();
           });
           page1.show();
       });
       
       hi.getToolbar().addCommandToSideMenu("Page 2", null, e->{
           page2=new Form("Page 2");
           page2.getToolbar().addMaterialCommandToRightBar("back", FontImage.MATERIAL_BACKSPACE, ev->{
               hi.show();
           });
           page2.show();
       });
       
       hi.getToolbar().addCommandToSideMenu("Page 3", null, e->{
           page3=new Form("Page 3");
           page3.getToolbar().addCommandToOverflowMenu("back", theme.getImage("back-command.png"), ev->{
               hi.show();
           });
           page3.show();
       });
        hi.show();
    }

    public void stop() {
        current = Display.getInstance().getCurrent();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = Display.getInstance().getCurrent();
        }
    }
    
    public void destroy() {
    }

}
